version: "3.8"
services:
  db:
    image: postgres
    container_name: uspto_db
    env_file:
      - .env
    ports:
      - "5437:5432"

  patent_fetcher:
    build: .
    image: patent_fetcher
    depends_on:
      - db
    env_file:
      - .env

  tests:
    build:
      context: .
      dockerfile: dockerfile-test
    image: pf_test_image
    depends_on:
      - db


